// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credentials.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCredential = `-- name: CreateCredential :one
INSERT INTO credentials (
    service,
    encrypted_service_username,
    description,
    encrypted_password,
    encryption_algorithm,
    user_id
    )
VALUES($1, $2, $3, $4, $5, $6)
RETURNING id, service, description, encryption_algorithm
`

type CreateCredentialParams struct {
	Service                  string      `json:"service"`
	EncryptedServiceUsername []byte      `json:"encrypted_service_username"`
	Description              pgtype.Text `json:"description"`
	EncryptedPassword        []byte      `json:"encrypted_password"`
	EncryptionAlgorithm      string      `json:"encryption_algorithm"`
	UserID                   uuid.UUID   `json:"user_id"`
}

type CreateCredentialRow struct {
	ID                  uuid.UUID   `json:"id"`
	Service             string      `json:"service"`
	Description         pgtype.Text `json:"description"`
	EncryptionAlgorithm string      `json:"encryption_algorithm"`
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (CreateCredentialRow, error) {
	row := q.db.QueryRow(ctx, createCredential,
		arg.Service,
		arg.EncryptedServiceUsername,
		arg.Description,
		arg.EncryptedPassword,
		arg.EncryptionAlgorithm,
		arg.UserID,
	)
	var i CreateCredentialRow
	err := row.Scan(
		&i.ID,
		&i.Service,
		&i.Description,
		&i.EncryptionAlgorithm,
	)
	return i, err
}

const deleteCredentialById = `-- name: DeleteCredentialById :one
DELETE FROM credentials
WHERE id = $1
RETURNING service
`

func (q *Queries) DeleteCredentialById(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, deleteCredentialById, id)
	var service string
	err := row.Scan(&service)
	return service, err
}

const getAllCredentialsForUserId = `-- name: GetAllCredentialsForUserId :many
SELECT id, service, description, encryption_algorithm 
FROM credentials
WHERE user_id = $1
`

type GetAllCredentialsForUserIdRow struct {
	ID                  uuid.UUID   `json:"id"`
	Service             string      `json:"service"`
	Description         pgtype.Text `json:"description"`
	EncryptionAlgorithm string      `json:"encryption_algorithm"`
}

func (q *Queries) GetAllCredentialsForUserId(ctx context.Context, userID uuid.UUID) ([]GetAllCredentialsForUserIdRow, error) {
	rows, err := q.db.Query(ctx, getAllCredentialsForUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllCredentialsForUserIdRow{}
	for rows.Next() {
		var i GetAllCredentialsForUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Service,
			&i.Description,
			&i.EncryptionAlgorithm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCredentialById = `-- name: GetCredentialById :one
SELECT id, service, encrypted_service_username, description, encrypted_password, encryption_algorithm, user_id, created_at, updated_at
FROM credentials
WHERE id = $1
`

func (q *Queries) GetCredentialById(ctx context.Context, id uuid.UUID) (Credential, error) {
	row := q.db.QueryRow(ctx, getCredentialById, id)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Service,
		&i.EncryptedServiceUsername,
		&i.Description,
		&i.EncryptedPassword,
		&i.EncryptionAlgorithm,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCredential = `-- name: UpdateCredential :one
UPDATE credentials
SET encrypted_password = $1,
    encryption_algorithm = $2,
    updated_at = NOW()
WHERE id = $3 AND user_id = $4
RETURNING id, service, description, encryption_algorithm
`

type UpdateCredentialParams struct {
	EncryptedPassword   []byte    `json:"encrypted_password"`
	EncryptionAlgorithm string    `json:"encryption_algorithm"`
	ID                  uuid.UUID `json:"id"`
	UserID              uuid.UUID `json:"user_id"`
}

type UpdateCredentialRow struct {
	ID                  uuid.UUID   `json:"id"`
	Service             string      `json:"service"`
	Description         pgtype.Text `json:"description"`
	EncryptionAlgorithm string      `json:"encryption_algorithm"`
}

func (q *Queries) UpdateCredential(ctx context.Context, arg UpdateCredentialParams) (UpdateCredentialRow, error) {
	row := q.db.QueryRow(ctx, updateCredential,
		arg.EncryptedPassword,
		arg.EncryptionAlgorithm,
		arg.ID,
		arg.UserID,
	)
	var i UpdateCredentialRow
	err := row.Scan(
		&i.ID,
		&i.Service,
		&i.Description,
		&i.EncryptionAlgorithm,
	)
	return i, err
}
