// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Operation struct {
	ID          pgtype.UUID      `json:"id"`
	UserID      pgtype.UUID      `json:"user_id"`
	Type        string           `json:"type"`
	Service     string           `json:"service"`
	ServiceID   pgtype.UUID      `json:"service_id"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type Service struct {
	ID                  pgtype.UUID      `json:"id"`
	Service             string           `json:"service"`
	ServiceUsername     []byte           `json:"service_username"`
	Description         pgtype.Text      `json:"description"`
	EncryptedPassword   []byte           `json:"encrypted_password"`
	EncryptionAlgorithm string           `json:"encryption_algorithm"`
	UserID              pgtype.UUID      `json:"user_id"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID                 pgtype.UUID      `json:"id"`
	Username           string           `json:"username"`
	PasswordHash       string           `json:"password_hash"`
	MasterKeySalt      pgtype.Text      `json:"master_key_salt"`
	EncryptedMasterKey pgtype.Text      `json:"encrypted_master_key"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
}
