// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Credential struct {
	ID                       uuid.UUID        `json:"id"`
	Service                  string           `json:"service"`
	EncryptedServiceUsername []byte           `json:"encrypted_service_username"`
	Description              pgtype.Text      `json:"description"`
	EncryptedPassword        []byte           `json:"encrypted_password"`
	EncryptionAlgorithm      string           `json:"encryption_algorithm"`
	UserID                   uuid.UUID        `json:"user_id"`
	CreatedAt                pgtype.Timestamp `json:"created_at"`
	UpdatedAt                pgtype.Timestamp `json:"updated_at"`
}

type Operation struct {
	ID        uuid.UUID        `json:"id"`
	UserID    uuid.UUID        `json:"user_id"`
	OpType    string           `json:"op_type"`
	Service   string           `json:"service"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID                 uuid.UUID        `json:"id"`
	Username           string           `json:"username"`
	PasswordHash       string           `json:"password_hash"`
	MasterKeySalt      string           `json:"master_key_salt"`
	EncryptedMasterKey string           `json:"encrypted_master_key"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
}
