// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOperation = `-- name: CreateOperation :one
INSERT INTO operations (
    user_id,
    type,
    service,
    service_id,
    description
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, type, service, service_id, description, created_at
`

type CreateOperationParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Type        string      `json:"type"`
	Service     string      `json:"service"`
	ServiceID   pgtype.UUID `json:"service_id"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateOperation(ctx context.Context, arg CreateOperationParams) (Operation, error) {
	row := q.db.QueryRow(ctx, createOperation,
		arg.UserID,
		arg.Type,
		arg.Service,
		arg.ServiceID,
		arg.Description,
	)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Service,
		&i.ServiceID,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getOperationsForService = `-- name: GetOperationsForService :many
SELECT id, user_id, type, service, service_id, description, created_at
FROM operations
WHERE service = $1 AND user_id = $2
`

type GetOperationsForServiceParams struct {
	Service string      `json:"service"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetOperationsForService(ctx context.Context, arg GetOperationsForServiceParams) ([]Operation, error) {
	rows, err := q.db.Query(ctx, getOperationsForService, arg.Service, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Operation{}
	for rows.Next() {
		var i Operation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Service,
			&i.ServiceID,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOperationsForUserId = `-- name: GetOperationsForUserId :many
SELECT id, user_id, type, service, service_id, description, created_at
FROM operations
WHERE user_id = $1
`

func (q *Queries) GetOperationsForUserId(ctx context.Context, userID pgtype.UUID) ([]Operation, error) {
	rows, err := q.db.Query(ctx, getOperationsForUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Operation{}
	for rows.Next() {
		var i Operation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Service,
			&i.ServiceID,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOperationDesc = `-- name: UpdateOperationDesc :exec
UPDATE operations
SET description = $1
WHERE id = $2 AND user_id = $3
`

type UpdateOperationDescParams struct {
	Description pgtype.Text `json:"description"`
	ID          pgtype.UUID `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateOperationDesc(ctx context.Context, arg UpdateOperationDescParams) error {
	_, err := q.db.Exec(ctx, updateOperationDesc, arg.Description, arg.ID, arg.UserID)
	return err
}
