// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operations.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOperation = `-- name: CreateOperation :exec
INSERT INTO operations (
    user_id,
    op_type,
    service,
    credential_id
)
VALUES ($1, $2, $3, $4)
`

type CreateOperationParams struct {
	UserID       uuid.UUID   `json:"user_id"`
	OpType       string      `json:"op_type"`
	Service      string      `json:"service"`
	CredentialID pgtype.UUID `json:"credential_id"`
}

func (q *Queries) CreateOperation(ctx context.Context, arg CreateOperationParams) error {
	_, err := q.db.Exec(ctx, createOperation,
		arg.UserID,
		arg.OpType,
		arg.Service,
		arg.CredentialID,
	)
	return err
}

const getOperationsForService = `-- name: GetOperationsForService :many
SELECT id, user_id, op_type, service, credential_id, created_at
FROM operations
WHERE service = $1 AND user_id = $2
`

type GetOperationsForServiceParams struct {
	Service string    `json:"service"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) GetOperationsForService(ctx context.Context, arg GetOperationsForServiceParams) ([]Operation, error) {
	rows, err := q.db.Query(ctx, getOperationsForService, arg.Service, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Operation{}
	for rows.Next() {
		var i Operation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OpType,
			&i.Service,
			&i.CredentialID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOperationsForUserId = `-- name: GetOperationsForUserId :many
SELECT id, user_id, op_type, service, credential_id, created_at
FROM operations
WHERE user_id = $1
`

func (q *Queries) GetOperationsForUserId(ctx context.Context, userID uuid.UUID) ([]Operation, error) {
	rows, err := q.db.Query(ctx, getOperationsForUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Operation{}
	for rows.Next() {
		var i Operation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OpType,
			&i.Service,
			&i.CredentialID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
