// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateOperation(ctx context.Context, arg CreateOperationParams) (Operation, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteServiceById(ctx context.Context, arg DeleteServiceByIdParams) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetAllServicesForUserId(ctx context.Context, userID pgtype.UUID) ([]Service, error)
	GetOperationsForService(ctx context.Context, arg GetOperationsForServiceParams) ([]Operation, error)
	GetOperationsForUserId(ctx context.Context, userID pgtype.UUID) ([]Operation, error)
	GetServiceById(ctx context.Context, id pgtype.UUID) (Service, error)
	GetUserById(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	UpdateOperationDesc(ctx context.Context, arg UpdateOperationDescParams) error
	UpdateService(ctx context.Context, arg UpdateServiceParams) error
	UpdateUserKey(ctx context.Context, arg UpdateUserKeyParams) error
	UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) (User, error)
	UpdateUserSalt(ctx context.Context, arg UpdateUserSaltParams) error
}

var _ Querier = (*Queries)(nil)
