// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateOperation(ctx context.Context, arg CreateOperationParams) error
	CreateService(ctx context.Context, arg CreateServiceParams) (CreateServiceRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteServiceById(ctx context.Context, arg DeleteServiceByIdParams) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetAllServicesForUserId(ctx context.Context, userID uuid.UUID) ([]GetAllServicesForUserIdRow, error)
	GetOperationsForService(ctx context.Context, arg GetOperationsForServiceParams) ([]Operation, error)
	GetOperationsForUserId(ctx context.Context, userID uuid.UUID) ([]Operation, error)
	GetServiceById(ctx context.Context, arg GetServiceByIdParams) (Service, error)
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	UpdateService(ctx context.Context, arg UpdateServiceParams) (UpdateServiceRow, error)
	UpdateUserKey(ctx context.Context, arg UpdateUserKeyParams) error
	UpdateUserPassHashAndKey(ctx context.Context, arg UpdateUserPassHashAndKeyParams) error
	UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) (User, error)
	UpdateUserSalt(ctx context.Context, arg UpdateUserSaltParams) error
}

var _ Querier = (*Queries)(nil)
