// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createService = `-- name: CreateService :one
INSERT INTO services (
    service,
    encrypted_service_username,
    description,
    encrypted_password,
    encryption_algorithm,
    user_id
    )
VALUES($1, $2, $3, $4, $5, $6)
RETURNING id, service, description, encryption_algorithm
`

type CreateServiceParams struct {
	Service                  string      `json:"service"`
	EncryptedServiceUsername []byte      `json:"encrypted_service_username"`
	Description              pgtype.Text `json:"description"`
	EncryptedPassword        []byte      `json:"encrypted_password"`
	EncryptionAlgorithm      string      `json:"encryption_algorithm"`
	UserID                   uuid.UUID   `json:"user_id"`
}

type CreateServiceRow struct {
	ID                  uuid.UUID   `json:"id"`
	Service             string      `json:"service"`
	Description         pgtype.Text `json:"description"`
	EncryptionAlgorithm string      `json:"encryption_algorithm"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (CreateServiceRow, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.Service,
		arg.EncryptedServiceUsername,
		arg.Description,
		arg.EncryptedPassword,
		arg.EncryptionAlgorithm,
		arg.UserID,
	)
	var i CreateServiceRow
	err := row.Scan(
		&i.ID,
		&i.Service,
		&i.Description,
		&i.EncryptionAlgorithm,
	)
	return i, err
}

const deleteServiceById = `-- name: DeleteServiceById :exec
DELETE FROM services
WHERE id = $1 AND user_id = $2
`

type DeleteServiceByIdParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteServiceById(ctx context.Context, arg DeleteServiceByIdParams) error {
	_, err := q.db.Exec(ctx, deleteServiceById, arg.ID, arg.UserID)
	return err
}

const getAllServicesForUserId = `-- name: GetAllServicesForUserId :many
SELECT id, service, description, encryption_algorithm 
FROM services
WHERE user_id = $1
`

type GetAllServicesForUserIdRow struct {
	ID                  uuid.UUID   `json:"id"`
	Service             string      `json:"service"`
	Description         pgtype.Text `json:"description"`
	EncryptionAlgorithm string      `json:"encryption_algorithm"`
}

func (q *Queries) GetAllServicesForUserId(ctx context.Context, userID uuid.UUID) ([]GetAllServicesForUserIdRow, error) {
	rows, err := q.db.Query(ctx, getAllServicesForUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllServicesForUserIdRow{}
	for rows.Next() {
		var i GetAllServicesForUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Service,
			&i.Description,
			&i.EncryptionAlgorithm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServiceById = `-- name: GetServiceById :one
SELECT id, service, encrypted_service_username, description, encrypted_password, encryption_algorithm, user_id, created_at, updated_at
FROM services
WHERE id = $1 and user_id = $2
`

type GetServiceByIdParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetServiceById(ctx context.Context, arg GetServiceByIdParams) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceById, arg.ID, arg.UserID)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Service,
		&i.EncryptedServiceUsername,
		&i.Description,
		&i.EncryptedPassword,
		&i.EncryptionAlgorithm,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateService = `-- name: UpdateService :one
UPDATE services
SET encrypted_password = $1,
    encryption_algorithm = $2,
    updated_at = NOW()
WHERE id = $3 AND user_id = $4
RETURNING id, service, description, encryption_algorithm
`

type UpdateServiceParams struct {
	EncryptedPassword   []byte    `json:"encrypted_password"`
	EncryptionAlgorithm string    `json:"encryption_algorithm"`
	ID                  uuid.UUID `json:"id"`
	UserID              uuid.UUID `json:"user_id"`
}

type UpdateServiceRow struct {
	ID                  uuid.UUID   `json:"id"`
	Service             string      `json:"service"`
	Description         pgtype.Text `json:"description"`
	EncryptionAlgorithm string      `json:"encryption_algorithm"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (UpdateServiceRow, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.EncryptedPassword,
		arg.EncryptionAlgorithm,
		arg.ID,
		arg.UserID,
	)
	var i UpdateServiceRow
	err := row.Scan(
		&i.ID,
		&i.Service,
		&i.Description,
		&i.EncryptionAlgorithm,
	)
	return i, err
}
