// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createService = `-- name: CreateService :one
INSERT INTO services (
    service,
    encrypted_service_username,
    description,
    encrypted_password,
    encryption_algorithm,
    user_id
    )
VALUES($1, $2, $3, $4, $5, $6)
RETURNING id, service, encrypted_service_username, description, encrypted_password, encryption_algorithm, user_id, created_at, updated_at
`

type CreateServiceParams struct {
	Service                  string      `json:"service"`
	EncryptedServiceUsername []byte      `json:"encrypted_service_username"`
	Description              pgtype.Text `json:"description"`
	EncryptedPassword        []byte      `json:"encrypted_password"`
	EncryptionAlgorithm      string      `json:"encryption_algorithm"`
	UserID                   pgtype.UUID `json:"user_id"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.Service,
		arg.EncryptedServiceUsername,
		arg.Description,
		arg.EncryptedPassword,
		arg.EncryptionAlgorithm,
		arg.UserID,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Service,
		&i.EncryptedServiceUsername,
		&i.Description,
		&i.EncryptedPassword,
		&i.EncryptionAlgorithm,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteServiceById = `-- name: DeleteServiceById :exec
DELETE FROM services
WHERE id = $1 AND user_id = $2
`

type DeleteServiceByIdParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteServiceById(ctx context.Context, arg DeleteServiceByIdParams) error {
	_, err := q.db.Exec(ctx, deleteServiceById, arg.ID, arg.UserID)
	return err
}

const getAllServicesForUserId = `-- name: GetAllServicesForUserId :many
SELECT id, service, encrypted_service_username, description, encrypted_password, encryption_algorithm, user_id, created_at, updated_at 
FROM services
WHERE user_id = $1
`

func (q *Queries) GetAllServicesForUserId(ctx context.Context, userID pgtype.UUID) ([]Service, error) {
	rows, err := q.db.Query(ctx, getAllServicesForUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Service,
			&i.EncryptedServiceUsername,
			&i.Description,
			&i.EncryptedPassword,
			&i.EncryptionAlgorithm,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServiceById = `-- name: GetServiceById :one
SELECT id, service, encrypted_service_username, description, encrypted_password, encryption_algorithm, user_id, created_at, updated_at
FROM services
WHERE id = $1
`

func (q *Queries) GetServiceById(ctx context.Context, id pgtype.UUID) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceById, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Service,
		&i.EncryptedServiceUsername,
		&i.Description,
		&i.EncryptedPassword,
		&i.EncryptionAlgorithm,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateService = `-- name: UpdateService :exec
UPDATE services
SET encrypted_service_username = $1,
    description = $2,
    encrypted_password = $3,
    encryption_algorithm = $4,
    updated_at = NOW()
WHERE id = $5 AND user_id = $6
`

type UpdateServiceParams struct {
	EncryptedServiceUsername []byte      `json:"encrypted_service_username"`
	Description              pgtype.Text `json:"description"`
	EncryptedPassword        []byte      `json:"encrypted_password"`
	EncryptionAlgorithm      string      `json:"encryption_algorithm"`
	ID                       pgtype.UUID `json:"id"`
	UserID                   pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) error {
	_, err := q.db.Exec(ctx, updateService,
		arg.EncryptedServiceUsername,
		arg.Description,
		arg.EncryptedPassword,
		arg.EncryptionAlgorithm,
		arg.ID,
		arg.UserID,
	)
	return err
}
